name: Book CI/CD

# 在 book 分支得到推送时候触发这个 Actions
on:
  push:
    branches:
      - book

jobs:

  book-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Prepare Env #配置 mdbook 环境
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Deploy Book #部署 book 到 Github Pages 上面
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: https://github.com/yaesey/HandSecondFabricGuide.git
          user_email: nnqyq@outlook.com
          publish_branch: master
          publish_dir: ./book
          keep_files: true
          commit_message: ${{ github.event.head_commit.message }}